CREATE TABLE "GCG_3100_LOT_INFO"(
 "PCK_NO" CHAR(7) NOT NULL ,
 "ORDER_NO" CHAR(7) NOT NULL ,
 "ORDER_SHIP_NO" CHAR(4) NOT NULL ,
 "ORDER_REC" CHAR(4) NOT NULL ,
 "PART" CHAR(20),
 "LOT" CHAR(15),
 "BIN" CHAR(6),
 "HEAT" CHAR(15),
 "SERIAL" CHAR(30),
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3),
 "LOC" CHAR(2),
 "STAT" CHAR(1));
